Script started on Sun 01 Mar 2020 06:34:22 PM PST
]0;tusharj1@zuma:~/hw4[tusharj1@zuma ~/hw4]$ m=[Kake
gcc -ansi -std=c99 -Wall -c PhotoLab.c -o PhotoLab.o
gcc -ansi -std=c99 -Wall -c FileIO.c -o FileIO.o
gcc -ansi -std=c99 -Wall -c Image.c -o Image.o
gcc -ansi -std=c99 -Wall -c Test_v2.c -o Test.o
gcc -ansi -std=c99 -Wall -c DIPs.c -o DIPs.o
gcc -ansi -std=c99 -Wall -c Advanced.c -o Advanced.o
ar rc libFilter.a Advanced.o DIPs.o
ranlib libFilter.a
gcc -Wall PhotoLab.o FileIO.o Image.o Test.o -L. -lFilter -o PhotoLab -lm
gcc -ansi -std=c99 -Wall -c -DDEBUG -c PhotoLab.c -o PhotoLab_DEBUG.o
gcc -ansi -std=c99 -Wall -c -DDEBUG Test_v2.c -o Test_DEBUG.o
gcc -Wall PhotoLab_DEBUG.o Test_DEBUG.o FileIO.o Image.o -L. -lFilter -o PhotoLabTest -lm
]0;tusharj1@zuma:~/hw4[tusharj1@zuma ~/hw4]$ ./PhotoLab

-------------------------
1: Load a PPM image
2: Save the image in PPM and JPEG format
3: Change the color image to black and white
4: Sharpen the image
5: Change the hue of image
6: Add Noise to an image
7: Posterize an image
8: Add Motion Blur to an image
9: Enlarge the picture by percentage
10: Crop a square portion of the image
11: Adjust the brightness and contrast of an image
12: Test all functions
13: Exit

-------------------------
Please make your choice: 12

-------------------------
1: Load a PPM image
2: Save the image in PPM and JPEG format
3: Change the color image to black and white
4: Sharpen the image
5: Change the hue of image
6: Add Noise to an image
7: Posterize an image
8: Add Motion Blur to an image
9: Enlarge the picture by percentage
10: Crop a square portion of the image
11: Adjust the brightness and contrast of an image
12: Test all functions
13: Exit

-------------------------
Please make your choice: 13
You exit the program.
]0;tusharj1@zuma:~/hw4[tusharj1@zuma ~/hw4]$ valgrind --leak-check=full ./PhotoLabTest
==43363== Memcheck, a memory error detector
==43363== Copyright (C) 2002-2012, and GNU GPL'd, by Julian Seward et al.
==43363== Using Valgrind-3.8.1 and LibVEX; rerun with -h for copyright info
==43363== Command: ./PhotoLabTest
==43363== 
LoadImage & SaveImage tested!

Black and White tested!

Sharpen Detection tested!

Hue tested!

Noise tested!

Posterization tested!

MotionBlur tested!

Enlarge tested!

Square tested!

Brightness and Contrast tested!

==43363== 
==43363== HEAP SUMMARY:
==43363==     in use at exit: 0 bytes in 0 blocks
==43363==   total heap usage: 72 allocs, 72 frees, 10,492,576 bytes allocated
==43363== 
==43363== All heap blocks were freed -- no leaks are possible
==43363== 
==43363== For counts of detected and suppressed errors, rerun with: -v
==43363== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 8 from 6)
]0;tusharj1@zuma:~/hw4[tusharj1@zuma ~/hw4]$ make clean
rm -f *.o *.jpg PhotoLab PhotoLabTest bw.ppm sharpen.ppm hue.ppm noise.ppm posterize.ppm blur.ppm enlarge.ppm square.ppm brightnessandcontrast.ppm libFilter.a libFileIO.a
]0;tusharj1@zuma:~/hw4[tusharj1@zuma ~/hw4]$ exit
exit

Script done on Sun 01 Mar 2020 06:35:49 PM PST
